// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/roverse-dashboard/Dashboard.tsx": () => import("../components/mockups/roverse-dashboard/Dashboard.tsx"),
  "./components/mockups/roverse-login/Login.tsx": () => import("../components/mockups/roverse-login/Login.tsx"),
  "./components/mockups/roverse-planning/Planning.tsx": () => import("../components/mockups/roverse-planning/Planning.tsx")
};
